package com.db.enums;

public enum Department {

    CARDIOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    DERMATOLOGY,
    ONCOLOGY,
    GYNECOLOGY,
    UROLOGY,
    OPHTHALMOLOGY,
    OTORHINOLARYNGOLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    NEPHROLOGY,
    RHEUMATOLOGY,
    PULMONOLOGY,
    PSYCHIATRY,
    EMERGENCY,
    GENERAL_SURGERY,
    PLASTIC_SURGERY,
    NEUROSURGERY,
    CARDIOVASCULAR_SURGERY,
    RADIOLOGY,
    LABORATORY,
    PHARMACY,
    PHYSIOTHERAPY,
    NUTRITION,
    ANESTHESIOLOGY


}
